services:
  insert-gossip:
    build: .
    container_name: insert-gossip
    # This allows you to run it manually: docker compose run insert-gossip
    # It will exit when done.
    profiles: ["tools"] # Don't start with normal 'up'
    environment:
      POSTGRES_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ln-history-database:5432/lnhistory
      # Map the internal path to where you mount the file
      GOSSIP_FILE_PATH: /data/gossip_store
    volumes:
      # MOUNT YOUR HUGE FILE HERE
      - ./import-data/gossip_store_minibolt:/data/gossip_store
    depends_on:
      - ln-history-database

  # chain-enricher:
  #   image: ghcr.io/ln-history/chain-enricher:0.1.1
  #   container_name: chain-enricher
  #   restart: always
  #   environment:
  #     POSTGRES_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ln-history-database:5432/lnhistory
  #     BITCOIN_RPCHOST: host.docker.internal
  #     BITCOIN_RPCPORT: 8332
  #     BITCOIN_RPCUSER: ${BITCOIN_RPCUSER}
  #     BITCOIN_RPCPASSWORD: ${BITCOIN_RPCPASSWORD}
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - ln-history-database


  # ===========================
  # DATABASE
  # ===========================
  ln-history-database:
    image: postgres:18.1
    container_name: ln-history-database
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: lnhistory
    volumes:
      # Persist data to host
      - ./ln-history-database-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer:5.4.1
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - ln-history-database

  # ===========================
  # OBSERVABILITY STACK
  # ===========================
  grafana:
    image: grafana/grafana:12.4.0-19913286788-ubuntu
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    # You must explicitly tell Prometheus where to store data if you change user
    # because the default CMD might try to use a root-owned path.
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    
  loki:
    image: grafana/loki:main-e106809
    container_name: loki
    restart: always
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
